# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'

    steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(agent.builddirectory)'
          Contents: '**'
          TargetFolder: '$(build.artifactstagingdirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        
- stage: Deploy
  jobs:
   - job: Deploy
     pool:
        vmImage: 'windows-latest'
      
     steps:
     - task: DownloadBuildArtifacts@1
       inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: 'drop'
         downloadPath: '$(System.ArtifactsDirectory)'

     - task: AzureResourceManagerTemplateDeployment@3
       inputs:
         deploymentScope: 'Resource Group'
         azureResourceManagerConnection: 'Free Trial(b154ce63-1c54-4e89-a530-fde4493d04d7)'
         subscriptionId: 'b154ce63-1c54-4e89-a530-fde4493d04d7'
         action: 'Create Or Update Resource Group'
         resourceGroupName: 'fnapprg'
         location: 'East US'
         templateLocation: 'Linked artifact'
         csmFile: '$(System.ArtifactsDirectory)/drop/*/template.json'
         csmParametersFile: '$(System.ArtifactsDirectory)/drop/*/parameters.json'
         deploymentMode: 'Incremental'
